### ISSUE TITLE
Code challenge, foreign key restraint issue

### ISSUE THREAD

**Issue by austinksmith** [procore/tacocopter#3]
Hi there, I started working on the code challenge and almost immediately encountered issues with running the command `rake db:setup`, it appears there is a bug in the provided sql file that is used to run the setup command. Perhaps I'm misunderstanding the challenge and what the scope of the challenge is as I was not told which branch to use specifically, that being said I tried all 3 branches and I thought I had removed any reference to the database by running `rake db:drop` as well as manually clearing the databases themselves. Yet the issue remains, unfortunately I can't tell if this is related to my development environment or if this is a legitimate bug as I usually develop on my macbook pro and I'm having some hardware issues with that at the moment so I'm developing using my laptop running Ubuntu 16.04 LTS.

I can successfully run `rake db:create`, and `rake db:migrate` but running `rake db:setup `or `rake db:seed` results in the following error.
![screenshot from 2016-08-15 21-22-17](https://cloud.githubusercontent.com/assets/2227747/17685022/61e335f2-632e-11e6-82c8-1a3af7bffc4b.png)

The remaining part of the challenge doesn't look like it's going to be very difficult however I'm unable to get past this part which from my understanding is needed to continue forward with the challenge. I'm willing to completely wipe out my development environment and start over if this is definitely an issue on my end but it seems odd that this would be related to my environment. 

This is what my database.yml file looks like currently

```
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tacocopter_development
  pool: 5
  username: tacocopter
  password: procore
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tacocopter_test
  pool: 5
  username: tacocopter
  password: procore
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tacocopter
  pool: 5
  username: tacocopter
  password: procore
  socket: /var/run/mysqld/mysqld.sock
```
